### PR TITLE
Don't escape already escaped data

### PR DESCRIPTION
**Pull request by aaron-collier**
This determines if the query string sent through the API gateway needs to be escaped or not. 

Fixes sul-dlss/rialto#249

### CODE REVIEW

**Comment by jcoyne** [comment]
Can you please add a test for this?

**Comment by aaron-collier** [comment]
@jcoyne quick unit test added for encode string showing that a non-encoded and an encoded string both return properly. Happy to add anything else to this ;-)

**Comment by jcoyne** [comment]
I'm wondering what is sending an unencoded query? Shouldn't we just return a 400 error in that case?

**Comment by aaron-collier** [comment]
@jcoyne if I send a `curl -d@./some/test/file.txt <API Gateway endpoint>` that isn't already encoded, it gets through the API without being encoded. I don't think we can always expect encoded queries, unless that's something we want to enforce. Perhaps, something to discuss.

**Comment by jcoyne** [comment]
@aaron-collier shouldn't the command be `curl --data-urlencode insert@some/test/file.txt <url>`?

**Comment by jcoyne** [comment]
@aaron-collier 
> The command-line options mentioned above all require that you provide properly encoded data, data you need to make sure already exists in the right format. While that gives you a lot of freedom, it is also a bit inconvenient at times.
> To help you send data you haven't already encoded, curl offers the --data-urlencode option. This option offers several different ways to URL encode the data you give it.
https://ec.haxx.se/http-post.html

**Comment by aaron-collier** [comment]
@jcoyne ah, perhaps. I was following what we did early in the loading tests. I'll test with this. Thx.

**Comment by aaron-collier** [comment]
@jcoyne - actually one thing that just dawned on me related to our testing last week is that if we get an unencoded query with problematic characters (i.e. unencoded "&") then this will cause the CPU spike/reboot/timeout cycle on Neptune that we saw. So, the better question here I think would be 1.) do we want to encode a non-encoded query before sending it on, or 2.) should we check if the string is encoded and return an error if it is not, but not send it along to neptune?

I will capture this better in the ticket above for discussion.

**Comment by jcoyne** [comment]
Yes, I think we should still check to make sure it is encoded, but raise an error if the client is not doing the right thing.  I think that's preferable than trying to fix the clients bad behavior.

**Comment by aaron-collier** [comment]
Per planning discussion, this will be updated to return an error.

**Pull request merged**
