### PR TITLE
Update message to conform to diagram

### PR DESCRIPTION
**Pull request by aaron-collier**
Updates message:
action -> Action
entities -> Entities
body -> Body

Note: This currently sends a blank body as sparql query bodies with embedded quotes are causing issues. Follow up PR to come.

### CODE REVIEW

**Comment by jcoyne** [comment]
Can we add a test to this PR?

**Comment by aaron-collier** [comment]
@jcoyne Sure, I can work on that. We specifically didn't earlier (per discussion with @mjgiarlo) but testing `main` is probably more important now.

**Comment by mjgiarlo** [comment]
How much do/should we care about the uppercase changes? if we make that change here, we will need to make it in other places too (in the ingest service and in trigger rebuild at least).

**Comment by mjgiarlo** [comment]
let's discuss in storytime today.

**Comment by mjgiarlo** [comment]
:+1: to the messaging case changes in this PR.

**Pull request merged**
